### ISSUE TITLE
incorrect monster spawner generation on version 1.20.1

### ISSUE THREAD

**Issue by 1KrazY0KykeR1** [FrozenBlock/WilderWild#254] opened 2023-06-25 14:52 UTC
for some reason, all generated monster spawners, except for those in the mine (poisonous spider spawner) and in the Fortress (Silverfish spawner), contain a pig spawn. game version 1.20.1. for example, I can cast the world with generation key "8888888888888888888888888888888", at coordinates 4681 -9 -950

**Comment by 1KrazY0KykeR1** [comment] 2023-06-25 14:54
I gave an example of the spawner, which is the easiest to reach. but you can generate any world and find any spawner there. I hope I'm not the only one with this problem

**Comment by Soro335** [comment] 2023-06-25 15:06
Can you send your mod list???

**Comment by 1KrazY0KykeR1** [comment] 2023-06-25 15:14
I have this problem even if only these two mods are installed: Wilder Wild and fabric api

**Comment by Taleuxss** [comment] 2023-06-30 19:45
same

**Comment by Treetrain1** [comment] 2023-07-05 12:49
additional info for this issue: does not happen with just frozenlib or frozenlib + nbt crafting, does happen with wilder wild

**Comment by Treetrain1** [comment] 2023-07-05 14:17
found something potentially useful for the fix
the `MonsterRoomFeature` class assigns the spawner an entity from a random selection from an array.
i looked at the array, and all the contents are null.

In Minecraft, when an entity id is null, it defaults to `minecraft:pig`, so maybe these are connected in some way
![image](https://github.com/FrozenBlock/WilderWild/assets/39657565/4baccedf-686c-426e-8d28-32178588e3d1)

**Comment by ZerbieSlug** [comment] 2023-07-11 05:26
Can confirm that I'm experiencing this issue in 1.20.1

It's 100% this mod causing the issue

**Comment by ZerbieSlug** [comment] 2023-07-12 02:00
BTW I tried playing on v2.0.5 (current version for 1.20.1 is 2.0.6) and it looks like this bug has been carried over into the current version

**Comment by Xfrtrex** [comment] 2023-07-12 04:37
Can confirm, im on a server with wilder wild, there is NO spawners in dungeons, they dont exist. its just pigs

**Comment by Treetrain1** [comment] 2023-07-21 02:22
will wait for further confirmation from @1KrazY0KykeR1 or other people before marking this as closed

**Comment by Treetrain1** [comment] 2023-07-25 17:33
Cannot reproduce on the latest version (2.1). Should be fixed.

**Closed by Treetrain1** 2023-07-25 17:33 UTC
Labels: bug
