### ISSUE TITLE
[Crash on launch] most recent version incompatible with Great Big World

### ISSUE THREAD

**Issue by steve-the-player** [FrozenBlock/WilderWild#327] opened 2023-12-16 19:59 UTC
**Description of the Bug Encountered**
Fatal error preventing game launch

**Steps To Reproduce**
1. Install GBW most recent version + dependencies 
2. Install WilderWild 2.2 or 2.2.1
3. try to launch game

**Expected Behavior**
Game launch

**Logs**
https://mclo.gs/qfiihS5

**Additional context**
seems to be an issue with the entity reach modifier mixin/class. 
Full log here in case mclogs link expires 
[2023-12-16-5.log](https://github.com/FrozenBlock/WilderWild/files/13693784/2023-12-16-5.log)

**Comment by AViewFromTheTop** [comment] 2023-12-16 20:04
We’re already aware of this and I’ve already looked at what causes this. It’s caused by CleoLib’s “compat” mixin for Reach Entity Attributes (which Wilder Wild uses for the Potion of Reaching,) which the dev obviously did ***not*** test as their mixin causes a ModifyConstant conflict.

**Comment by AViewFromTheTop** [comment] 2023-12-16 20:07
Either me or Treetrain will issue a fix in the next version, but it is honestly my recommendation to pick either Great Big World or Wilder Wild for the time being. CleoLib, at least, uses a TON of aggressive mixins that can cause potential issues or prevent other mods from running their behavior, which is troublesome enough.
On top of that, neither Great Big World nor CleoLib have been updated in the last four months so there’s no reason to expect a fix on their side.
The best we can do is update our fork of Reach Entity Attributes to not load the ItemStack mixin if CleoLib is installed and hope their compat mixin will provide the behavior we want. It should work, but I just wanted to explain that since those mods are clearly no longer supported by their developer.

**Comment by Poopooracoocoo** [comment] 2023-12-16 20:09
https://github.com/jack-zisa/CreoLib/issues/13

**Comment by AViewFromTheTop** [comment] 2023-12-16 20:09
Actually, no. I remember how CleoLib’s mixin is setup and it’ll completely ignore Reach Entity Attributes’ behavior if we were to “fix” it. Both REA and CL need to be updated to use MixinExtras for a proper fix in the best case scenario, specifically ModifyExpressionValue.

**Comment by steve-the-player** [comment] 2023-12-19 15:50
Well, the good news is, this issue will resolve itself in future minecraft versions; 1.21 will have a command (and datapack attribute) to modify the distance something can reach, completely vanilla, so both mixins will become obsolete and unnecessary

**Comment by AViewFromTheTop** [comment] 2024-01-06 23:04
Closing as this isn't our issue. Should be tracked in CleoLib.

**Closed by AViewFromTheTop** 2024-01-06 23:04 UTC
Labels: bug
