### ISSUE TITLE
"Failed to access world" crash

### ISSUE THREAD

**Issue by ekd403** [FrozenBlock/WilderWild#364] opened 2024-04-04 04:20 UTC
**Description of the Bug Encountered**
Every time I try to load a world that I've already created with this mod, it causes a loading error and produces "failed to access world".  Error occurs with mods and without other mods.

**Steps To Reproduce**
1. Load game
2. Create world
3. Try to relaunch world
4. Crash

**Expected Behavior**
Expected to load my world.

**Screenshots**

**Logs**

**Additional context**

**Comment by FrederikSchiller** [comment] 2024-04-16 18:48
Hi! Same issue here. I was using V 2.3.3 (1.20.1) but after downgrading to 2.3.2 the problem was gone. maybe it helps you aswell

**Comment by gendernonconforming** [comment] 2024-04-18 15:09
Same issue, and solution above worked for me as well. Seems like an incompatibility with 2.3.3 and 1.20.1

**Comment by Treetrain1** [comment] 2024-04-18 17:11
I cannot reproduce this. Please provide more information

**Comment by FrederikSchiller** [comment] 2024-04-18 17:20
I have a long Modlist, so i was unable to pinpoint the exact problem.

![Screenshot 2024-04-18 191906](https://github.com/FrozenBlock/WilderWild/assets/14977977/ee5746b0-a7e7-4de0-a6ef-d03ed130e003)

This is when ERRORs start to occur:

[20:02:54] [Worker-ResourceReload-14/ERROR]: Couldn't load tag creategoggles:modifier/goggle_incompatible as it is missing following references: mekanism:mekasuit_helmet (from fabric)
[20:02:54] [Worker-ResourceReload-14/ERROR]: Couldn't load tag minecraft:trim_materialss as it is missing following references: creategoggles:goggle_material (from fabric)
[20:02:54] [Worker-ResourceReload-15/ERROR]: Couldn't load tag minecraft:fan_transparent as it is missing following references: create:void_steel_bars (from fabric)
[20:02:54] [Worker-ResourceReload-10/ERROR]: Couldn't parse element loot_tables:ctov:chests/village/village_forager
com.google.gson.JsonSyntaxException: Missing expand, expected to find a Boolean
	at net.minecraft.class_3518.method_15270(class_3518.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_91$class_92.method_450(class_91.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.class_91$class_92.method_443(class_91.java:72) ~[client-intermediary.jar:?]
	at net.minecraft.class_85$class_90.method_441(class_85.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_85$class_90.method_424(class_85.java:129) ~[client-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:463) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15272(class_3518.java:471) ~[client-intermediary.jar:?]
	at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:463) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15283(class_3518.java:481) ~[client-intermediary.jar:?]
	at net.minecraft.class_52$class_54.method_340(class_52.java:250) ~[client-intermediary.jar:?]
	at net.minecraft.class_52$class_54.deserialize(class_52.java:246) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
	at net.minecraft.class_8490.method_51205(class_8490.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_8490.method_51204(class_8490.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_60.method_51195(class_60.java:55) ~[client-intermediary.jar:?]
	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_60.method_51189(class_60.java:55) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[20:02:54] [Render thread/ERROR]: Parsing error loading recipe supplementaries:integration/lapis_bricks_fd
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an item
	at net.minecraft.class_1856.method_8107(class_1856.java:167) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[client-intermediary.jar:?]
	at vectorwing.farmersdelight.common.crafting.CuttingBoardRecipe$Serializer.fromJson(CuttingBoardRecipe.java:176) ~[FarmersDelight-1.20.1-2.0.17+refabricated.jar:?]
	at vectorwing.farmersdelight.common.crafting.CuttingBoardRecipe$Serializer.method_8121(CuttingBoardRecipe.java:166) ~[FarmersDelight-1.20.1-2.0.17+refabricated.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18857(class_310.java:21517) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_45694(class_7196.java:188) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41891(class_7196.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41899(class_7196.java:202) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41894(class_7196.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:402) ~[client-intermediary.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:327) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.10.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
[20:02:54] [Render thread/WARN]: Suspicious fluid amount in recipe [farmersdelight:integration/create/filling/chocolate_pie]: 500
[20:02:54] [Render thread/ERROR]: Parsing error loading recipe supplementaries:integration/ash_bricks_fd
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an item
	at net.minecraft.class_1856.method_8107(class_1856.java:167) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[client-intermediary.jar:?]
	at vectorwing.farmersdelight.common.crafting.CuttingBoardRecipe$Serializer.fromJson(CuttingBoardRecipe.java:176) ~[FarmersDelight-1.20.1-2.0.17+refabricated.jar:?]
	at vectorwing.farmersdelight.common.crafting.CuttingBoardRecipe$Serializer.method_8121(CuttingBoardRecipe.java:166) ~[FarmersDelight-1.20.1-2.0.17+refabricated.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18857(class_310.java:21517) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_45694(class_7196.java:188) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41891(class_7196.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41899(class_7196.java:202) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41894(class_7196.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:402) ~[client-intermediary.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:327) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.10.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
[20:02:54] [Render thread/WARN]: Suspicious fluid amount in recipe [farmersdelight:integration/create/mixing/pie_crust_from_mixing]: 250
[20:02:54] [Render thread/INFO]: Loaded 29 recipes
[20:02:55] [Render thread/INFO]: Loading config MiscConfig from wilderwild
[20:02:55] [Render thread/INFO]: Saving config MiscConfig from wilderwild
[20:02:55] [Render thread/INFO]: Loaded 5975 advancements
[20:02:55] [Render thread/WARN]: Could not decode GlobalLootModifier with json id supplementaries:ash_from_burning_mobs - error: Unknown registry key in ResourceKey[minecraft:root / porting_lib:global_loot_modifier_serializers]: moonlight:add_item
[20:02:55] [Render thread/WARN]: Could not decode GlobalLootModifier with json id supplementaries:straw_from_flax - error: Unknown registry key in ResourceKey[minecraft:root / porting_lib:global_loot_modifier_serializers]: moonlight:add_item
[20:02:55] [Render thread/WARN]: Could not decode GlobalLootModifier with json id supplementaries:fishing_antique_ink - error: Unknown registry key in ResourceKey[minecraft:root / porting_lib:global_loot_modifier_serializers]: moonlight:add_item
[20:02:55] [Render thread/WARN]: Could not decode GlobalLootModifier with json id supplementaries:fishing_antique_ink_treasure - error: Unknown registry key in ResourceKey[minecraft:root / porting_lib:global_loot_modifier_serializers]: moonlight:add_item
[20:02:55] [Render thread/INFO]: [Fabric Seasons] Successfully loaded 33 custom crop configs.
[20:02:55] [Render thread/INFO]: Loaded 27 flute songs
[20:02:55] [Render thread/INFO]: Finished additional setup in 21 ms
[20:02:55] [Render thread/INFO]: Loaded 78 block growths configurations
[20:02:55] [Render thread/INFO]: Loaded 14 liquid generators configurations
[20:02:55] [Render thread/INFO]: Applied 7 data villager trades
[20:02:55] [Render thread/WARN]: Failed to read level Maybe Yesssss _ data
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
	at sun.nio.ch.FileDispatcherImpl.write(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:?]
	at sun.nio.ch.FileChannelImpl.write(Unknown Source) ~[?:?]
	at net.minecraft.class_5125.method_26803(class_5125.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_32$class_5143.<init>(class_32.java:398) ~[client-intermediary.jar:?]
	at net.minecraft.class_32.method_52236(class_32.java:377) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41901(class_7196.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41899(class_7196.java:193) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41897(class_7196.java:220) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.handler$cfo000$frozenlib$frozenLib$preventBackupScreenAndProceed(class_7196.java:542) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41898(class_7196.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41899(class_7196.java:220) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41894(class_7196.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:402) ~[client-intermediary.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:327) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.10.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
[20:03:00] [CullThread/INFO]: [STDOUT]: Shutting down culling task!
[20:03:00] [Render thread/INFO]: Stopping!
[20:03:00] [Render thread/INFO]: Stopping JEI
[20:03:00] [Render thread/INFO]: Stopping JEI
[20:03:00] [Render thread/INFO]: Sending Runtime Unavailable...
[20:03:00] [Render thread/INFO]: Stopping JEI GUI
[20:03:00] [Render thread/INFO]: Sending Runtime Unavailable took 505.4 ?s

I hope this helps!

**Comment by AViewFromTheTop** [comment] 2024-04-18 17:44
> I have a long mod list, so I was unable to pinpoint the exact problem.
> 
> ![Screenshot 2024-04-18 191906](https://private-user-images.githubusercontent.com/14977977/323700276-ee5746b0-a7e7-4de0-a6ef-d03ed130e003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NjI1MTgsIm5iZiI6MTcxMzQ2MjIxOCwicGF0aCI6Ii8xNDk3Nzk3Ny8zMjM3MDAyNzYtZWU1NzQ2YjAtYTdlNy00ZGUwLWE2ZWYtZDAzZWQxMzBlMDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE3NDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZmNjZGZmMWNhYWU2ZTg0NmVjNmIwOTM3N2M0YWNkNDk3MDdkYmU0M2UwMWQyYTRlNzY4ZjY4Mjc0YjdkNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FHIYKwvxDXAm_khuvAUZuTERNZNpezwyNcBV4QsEFwI)
> 
> This is the error, but I can't determine which conflicts are responsible: java.io.IOException: The process cannot access the file because another process has locked a portion of the file.

Can you reproduce this with the Experimental config option from FrozenLib turned off?

**Comment by AViewFromTheTop** [comment] 2024-04-18 17:44
If not, it’s likely best we just remove it.

**Comment by AViewFromTheTop** [comment] 2024-05-02 16:46
I'll be closing this issue as there has not been a follow-up.
Please disable the config option in FrozenLib that controls the experimental warning menu.
Thank you.

**Closed by AViewFromTheTop** 2024-05-02 16:46 UTC
Labels: bug, worldgen, crash, awaiting response, cannot reproduce
