### ISSUE TITLE
Crash with Sodium

### ISSUE THREAD

**Issue by Mettod99** [FrozenBlock/WilderWild#242] opened 2023-05-19 21:31 UTC
**Description of the error found**
The game crashes when loading a world with the Sodium mod installed.

**Reproduction Procedures**
1. Try opening the world with the Sodium and Wilder Wild mod installed.

**Expected Behavior**
The world should open.

**Comment by Treetrain1** [comment] 2023-05-20 07:32
Please provide more information.

Game version
Sodium version
Wilder Wild version

Log or crash file

**Comment by Mettod99** [comment] 2023-05-20 09:05
**Game Version**
Minecraft: 1.19.4
Fabric: 0.14. 19

**Mod versions**
Sodium: 0.4.11+build.26
Wilder Wild: 2.0-Fabric+1.19.4
Fabric API: [0.81.1+1.19.4]

**Crash Report**
[crash-2023-05-20_10.59.00-client.txt](https://github.com/FrozenBlock/WilderWild/files/11521936/crash-2023-05-20_10.59.00-client.txt)

**Comment by Soro335** [comment] 2023-05-20 09:21
duplicate of #240

**Closed by Soro335** 2023-05-20 09:21 UTC
Labels: bug, crash, mod compatibility, awaiting response

**Comment by Soro335** [comment] 2023-05-20 09:24
use sodium 0.4.10, because version 0.4.11 is unstable and removed from modrinth
