### ISSUE TITLE
Game crashes when exploring my world

### ISSUE THREAD

**Issue by AshelySoftpaws21** [FrozenBlock/WilderWild#301] opened 2023-09-10 02:37 UTC
**Description of the Bug Encountered**

**Steps To Reproduce**
1.  Load world 
2.  Walk in a random direction for a long time (or elytra fly quickly)

**Expected Behavior**
Keep loading new chunks

**Logs**
https://pastebin.com/yjeSZRNQ

**Additional context**
 Modpack is Quantum Freedom

**Comment by AViewFromTheTop** [comment] 2023-09-10 05:38
@Treetrain1 can you merge #300 because that fixes this exact issue

**Comment by noah1510** [comment] 2023-09-10 19:09
I found the cause.
The crash happens because of the async world generation.
Disabling this causes the problems to no longer happen.

**Comment by AshelySoftpaws21** [comment] 2023-09-11 02:12
> 

How does one disable that?

**Comment by noah1510** [comment] 2023-09-11 09:38
go to the config folder -> open c2me.toml -> scroll down until you see `threadedWorldGen` -> change the default next to `enabled`to false.

**Comment by AshelySoftpaws21** [comment] 2023-09-12 14:20
Thanks!

**Comment by Treetrain1** [comment] 2023-09-25 00:31
should be fixed

**Closed by Treetrain1** 2023-09-25 00:31 UTC
Labels: bug
