### ISSUE TITLE
Ancient Horns in loot tables don't have Instrument NBT, thereby not working.

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/WilderWild#104] opened 2022-08-21 22:16 UTC

**Comment by BluePhoenixLOL** [comment] 2022-08-21 22:31
uh oh

**Comment by BluePhoenixLOL** [comment] 2022-08-21 22:32
oh well you just drop them and then pick them back up but thats still a bad bug, how do goat horns do it in outposts?

**Comment by BluePhoenixLOL** [comment] 2022-08-21 23:42
duplicate of: https://github.com/FrozenBlock/WilderWild/issues/105

**Closed by BluePhoenixLOL** 2022-08-21 23:42 UTC
Labels: bug, duplicate, invalid
