### ISSUE TITLE
[Crash] Fabric 1.21 - Wilder Wild appears to be conflicting with Extended Block Shapes

### ISSUE THREAD

**Issue by Gamemassa** [FrozenBlock/WilderWild#399] opened 2024-07-15 15:04 UTC
**Version**
- Minecraft 1.21
- Fabric Loader 0.16.0
- Fabric API 0.100.7
- Wilder Wild 2.4.6 for MC 1.21

**Description of the Bug Encountered**
Game crashes on startup when both Wilder Wild and [Extended Block Shapes](https://www.curseforge.com/minecraft/mc-mods/extended-block-shapes) are installed.

**Logs**
- Crash Report:
https://mclo.gs/zVhXnE2

- Latest.log:
https://mclo.gs/qrnmxXo

**Comment by Treetrain1** [comment] 2024-07-15 15:10
Duplicate of #391
It's an issue on their side we cannot fix

**Closed by Treetrain1** 2024-07-15 15:10 UTC
Labels: bug

**Comment by Gamemassa** [comment] 2024-07-15 15:12
> Duplicate of #391 It's an issue on their side we cannot fix

Oh, gotcha. Thanks. Looks like it was fixed with the latest version of BRRP, so I'll try that, and if it's still not working I'll tell the Extended Block Shapes team.
