### ISSUE TITLE
Overworld is removed from world_gen_settings when QuiltDataFixes used with Lithium and custom ChunkGenerator class

### ISSUE THREAD

**Issue by quiqueck** [FrozenBlock/WilderWild#268] opened 2023-07-16 08:22 UTC
I opened an Issue for this over at Lithium, but since I am not sure exactly what is causing the issue and the Qulit team mentioned, that this is a re-implementation from this Mod, I'll repost it here:

CaffeineMC/lithium-fabric#480

The original report was this issue: quiqueck/BCLib#113

**Comment by Treetrain1** [comment] 2023-07-16 09:56
Additional info: Adding `mixin.alloc=false` to Lithium's mixin config seems to fix the issue
will look further into it to try to narrow it down

**Comment by Treetrain1** [comment] 2023-07-18 17:13
There have been some changes to our port of QSL's DataFixerUpper API in 2.0.5
This is exactly the cause
I'll work on it

**Comment by Treetrain1** [comment] 2023-07-18 20:35
> There have been some changes to our port of QSL's DataFixerUpper API in 2.0.5 This is exactly the cause I'll work on it

I've managed to implement a fix by adding a config for disabling certain `DataFixTypes` from running through the DataFixerUpper API and then adding `WORLD_GEN_SETTINGS` by default.
In The Quilt Project's original API, `DataFixTypes.WORLD_GEN_SETTINGS` (as far as I know) was not used, so no functionality has been lost compared to the original.

The fix will be included in the next version of FrozenLib and Wilder Wild

**Closed** 2023-07-18 20:38 UTC
Labels: bug

**Comment by AViewFromTheTop** [comment] 2023-07-18 20:48
That’s should be 2.1 uwu
