### ISSUE TITLE
Opening Recipe Book causes extreme lag until closed with BetterMinecraft

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#192] opened 2022-12-16 19:08 UTC
## __We are currently unable to reproduce this bug. Any information regarding this issue from those who are experiencing it would be greatly appreciated.__

**Description of the Bug Encountered**

Opening the recipe book when using versions of BetterMinecraft that include Wilder Wild causes the game to slow down extremely until the recipe book is closed.

--- 

**Steps To Reproduce**

*ACCURATE INFORMATION PENDING*
1. Run latest version of BetterMinecraft
2. Open any world
3. Open inventory (and, by extension, recipe book)
4. Observe lag

--- 

**Logs**

*INFORMATION PENDING*

--- 

**Additional context**

- Happens client-side
- Is oddly subjective
  - only happens in multiplayer?
  - only happens in certain worlds?
  - only happens to certain people?
- Removing Wilder Wild fixes this issue
  - need more information regarding earlier versions of the mod
~~- Likely caused by NBT crafting mod~~
  ~~- does removing the recipe for copper horns fix it?~~
   ~~- No -> does removing the nbt crafting dependency in addition to the crafting recipes fix it?~~
    ~~- Yes -> see potential solutions~~

--- 

**Potential Solutions**
~~- Release separate versions without Copper Horn recipes for BetterMC to use~~
~~- Make each Copper Horn instrument a separate item rather than relying on NBT~~
~~- Use a separate NBT Crafting mod, or make our own~~

**Comment by Hellession** [comment] 2022-12-17 02:20
Hello,

In the LunaPixel Studios server (Better MC creators), I was asked to post about what we've found here.
I think we've found at least a part of what this issue is causing, but it only happens in relation to another specific mod.

**Mods involved**
* [Tom's Simple Storage Mod](https://www.curseforge.com/minecraft/mc-mods/toms-storage)
* Wilder Wild

**Reproduction**
1. Attain a Tom's Simple Storage Mod Terminal storage system with a working Terminal.
2. Put a large amount of items in that storage system. The more items are present, the more lag there would be.
3. Open the terminal.
4. Open the recipe book. (The game should experience a freeze or a lag spike at this point)
5. Perform any inventory item - take an item, place an item, right click an item, etc. (Each action will cause a lag spike)

**Evidence of how I reproduced it**
* I started fresh with the v12.5 of the Better MC modpack and then removed the Wilder Wild mod at first.
* I then created a world and built a small storage terminal with Tom's Simple Storage Mod next to a Full Beacon.
* Then I dumped a bunch of random items into it and bound an Advanced Wireless Terminal to it.
After a restart, using the Wireless Terminal, I recorded this video, showing _very little lag_ (NO Wilder Wild):
https://user-images.githubusercontent.com/26817396/208218440-299336b6-e411-430f-a2f0-b33c14a4961f.mp4
[Here is the log file of the Minecraft instance where I recorded that.](https://gist.github.com/Hellession/40a0b777c4dd76f30092eb53a393446e#file-latest-sp-without-wilder-wild-log)

* Afterwards, I added the Wilder Wild BACK into the modpack and launcher the world again.
Then I tried using the Wireless Terminal again with the recipe book open. I recorded this video (unfortunately this one is really compressed due to Github quality limits):
https://user-images.githubusercontent.com/26817396/208218807-bd50bfda-5cc2-406c-a0ae-81bbeb09cca2.mp4
If you look at the bottom left, you can notice that the lag spikes are a lot more noticeable - they get worse with bigger storages too. It didn't look like errors were being spammed in the logs, but [here is the log file of this attempt](https://gist.github.com/Hellession/40a0b777c4dd76f30092eb53a393446e#file-latest-sp-with-wilder-wild-log).

I wish I could also share the world file which I used, but these GitHub file limits are really limiting me right now...

**Comment by MerpisMe** [comment] 2022-12-17 03:22
this is *extremely* useful information, thank you so much!

**Comment by AViewFromTheTop** [comment] 2022-12-19 18:32
well here's something- you can't use a wireless terminal and access the recipe book at the same time
so..

**Comment by AViewFromTheTop** [comment] 2022-12-19 18:34
yes that was meant to send to disc easier
i need help cause i cant watch the vids lmao

**Comment by AViewFromTheTop** [comment] 2022-12-21 19:10
not a wilder wild issue- this is undoubtedly caused by another mod.
our itemstackmixin doesnt cause this, nor does nbtcrafting. ive tested by removing both.

**Comment by AViewFromTheTop** [comment] 2023-03-29 17:11
Closing this because not only does anyone want to solve their own issues, but we’re also being wrongfully blamed for this

**Closed by AViewFromTheTop** 2023-03-29 17:11 UTC
Labels: mod compatibility, cannot reproduce

**Comment by AViewFromTheTop** [comment] 2023-03-29 17:12
in other words im not going to bother stressing over an issue that isn’t ours and I think the rest of the team feels the same way
