### ISSUE TITLE
WilderWild 2.3 conflict with Sodium 0.5.5

### ISSUE THREAD

**Issue by adriancpp** [FrozenBlock/WilderWild#345] opened 2024-02-08 22:26 UTC
**Description of the Bug Encountered**
Error from log pointed in screenshot:
`[22:49:32] [Render thread/ERROR]: Resource pack 'wilderwild' replaces core shader 'rendertype_translucent.fsh'`

**Steps To Reproduce**
1. Install Fabric 1.20.4, put in mods `sodium-fabric-mc1.20.3-0.5.5.jar `and `WilderWild-2.3-Fabric+1.20.4.jar` files, run game.
2. In main menu of game, u will see error showed in screenshoot.

**Expected Behavior**
Mod looks like its working, while playing game doesnt crashed or produce any errors, just problem is annyoing when u see this pop up every time when you run the game.

**Screenshots**
![Screenshot 2024-02-08 at 23 22 50](https://github.com/FrozenBlock/WilderWild/assets/47180493/2a1e9118-8767-4ded-83e3-7dcfb11fe094)

**Logs**
[latest.log](https://github.com/FrozenBlock/WilderWild/files/14215278/latest.log)

**Additional context**
i just take a look and its about that file in your source code: 
src/main/resources/assets/minecraft/shaders/core/rendertype_translucent.fsh

in the same time i expected that i will find the same file in sodium source code but no... so there my knowledge of fabric is ending :p

**Comment by AViewFromTheTop** [comment] 2024-02-09 19:06
Have you tried using the latest version of Sodium? I can't reproduce it on there. There's a good chance it's caused by another mod that impacts rendering.

**Comment by AViewFromTheTop** [comment] 2024-02-09 19:10
Might be Iris.

**Comment by AViewFromTheTop** [comment] 2024-02-09 19:25
This should hopefully be fixed in the next release by separating it into a resource pack that won't be enabled if sodium or iris are present.

**Comment by Treetrain1** [comment] 2024-02-11 00:09
Use Sodium 0.5.8

**Closed by Treetrain1** 2024-02-11 00:09 UTC
Labels: bug, mod compatibility, awaiting response, cannot reproduce

**Comment by Treetrain1** [comment] 2024-02-11 00:18
AViewFromTheTop's solution has been reverted, as this doesn't happen on 1.20.1 or 1.20.2, and only happens on 0.5.5 for 1.20.3/1.20.4
