### ISSUE TITLE
Minecraft 1.20 crash when loading world with wilderwild 2.1

### ISSUE THREAD

**Issue by aotusoft** [FrozenBlock/WilderWild#273] opened 2023-07-22 10:59 UTC
First of all I'm sorry I modified the mod's fabric.mod.json file so that it works on minecraft 1.20

When I set Custom Grass Generation to false the game will crash when loading the world. After setting to true, the game can load the world normally

By the way, can you give an option to adjust the pollen spawned？

[minecraft-exported-crash-info-2023-07-22T18-42-58.zip](https://github.com/FrozenBlock/WilderWild/files/12136221/minecraft-exported-crash-info-2023-07-22T18-42-58.zip)

**Comment by AViewFromTheTop** [comment] 2023-07-22 11:33
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / wilderwild:rainforest]=net.minecraft.class_1959@7c62e1ea}, Reference{ResourceKey[minecraft:worldgen/biome / minecraft:old_growth_birch_forest]=net.minecraft.class_1959@53a221e2}]

**Comment by Treetrain1** [comment] 2023-07-22 18:51
Fixed in 2.1.1 (future release)

**Closed** 2023-07-22 18:51 UTC
Labels: bug
