### ISSUE TITLE
WilderWild + BetterX + Moonlight Lib causes a crash on startup

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [FrozenBlock/WilderWild#85] opened 2022-08-14 16:12 UTC
**MC** 1.19.2
**[QSL](https://modrinth.com/mod/qsl)** 4.0.0 beta 7
**WilderWild** 1.0.2
**[Moonlight Lib](https://www.curseforge.com/minecraft/mc-mods/selene)** 2.0.16 (it's not needed for any of the mods, only to reproduce the crash; I personally need it for the mod called [Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries) which doesn't have to be installed to reproduce the crash)
**[BCLib](https://www.curseforge.com/minecraft/mc-mods/bclib)** 2.0.20
**[BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend)** 2.0.11
**[BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether)** 7.0.9

To reproduce:

1. Install WilderWild, Moonlight and BCLib
2. Install either BetterEnd or BetterNether (or both, in which case BetterNether will be blamed for the crash)
3. Launch the game and crash

BetterEnd crash has something to do with `betterend:mossy_glowshroom`, BetterNether with `betternether:temp_patch_twisting_vine`. Not sure what part of WilderWild would try to modify those.

Oddly enough, BetterX mods don't seem to be incompatible with WilderWild on their own, but only with Moonlight present. Let me know if I need to report the issue to them or if it's something you can fix.

Removing either WilderWild, Moonlight Lib or both BetterX mods lets the game start normally.

Logs include latest.log and crash log for the BetterEnd crash, but only the latest.log for BetterNether, because it does not generate a crash log: https://gist.github.com/Footage2-Amply-Pounce/e7506db63847f6f7f315af3cddee93c6

**Comment by MerpisMe** [comment] 2022-08-15 18:51
this is definitely due to us overriding feature placement

**Comment by xanthian** [comment] 2022-08-16 19:51
Same issue with BetterNether crashing when WilderWorld is installed.

<![CDATA[Minecraft has crashed!]]>
<![CDATA[net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at org.betterx.betternether.registry.NetherBlocks.<clinit>(NetherBlocks.java:762)
	at org.betterx.betternether.entity.EntityFirefly.<clinit>(EntityFirefly.java:549)
	at org.betterx.betternether.registry.NetherEntities.<clinit>(NetherEntities.java:152)
	at net.minecraft.class_5135.handler$zmd000$hasDefinition(class_5135.java:531)
	at net.minecraft.class_5135.method_26875(class_5135.java)
	at net.minecraft.class_5135.method_26876(class_5135.java:176)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at net.minecraft.class_5135.method_26872(class_5135.java:178)
	at net.minecraft.class_2966.method_17598(class_2966.java:136)
	at net.minecraft.client.main.Main.method_44604(Main.java:162)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: java.lang.IllegalStateException: Feature configuration for betternether:temp_patch_twisting_vine can not be null!
	at org.betterx.bclib.api.v3.levelgen.features.BCLFeatureBuilder.buildAndRegister(BCLFeatureBuilder.java:226)
	at org.betterx.bclib.api.v3.levelgen.features.BCLFeatureBuilder.build(BCLFeatureBuilder.java:238)
	at org.betterx.bclib.api.v3.levelgen.features.BCLFeatureBuilder.inlinePlace(BCLFeatureBuilder.java:242)
	at org.betterx.betternether.registry.features.configured.NetherVines.<clinit>(NetherVines.java:113)

**Comment by Treetrain1** [comment] 2022-08-17 23:33
I am not sure if this is something we can fix.
You may need to make an issue on their side.

**Comment by Xfrtrex** [comment] 2022-08-23 00:13
Seems to crash without moonlight too.

**Comment by Treetrain1** [comment] 2022-10-12 00:20
Fixed on BetterX's side

**Closed by Treetrain1** 2022-10-12 00:20 UTC
Labels: todo, worldgen, crash, mod compatibility, high priority
