### ISSUE TITLE
3.0.2-mc1.20.4 FrozenLib Uses Java 21 Instead Of 17

### ISSUE THREAD

**Issue by EfficientStinkbug** [FrozenBlock/WilderWild#426] opened 2024-10-26 07:58 UTC
**Description of the Bug Encountered**

Edit: Please read the comment first, the issue is basically solved.

In advance: I'm not sure if it's becuase of Wilder Wild or Friends&Foes, but it worked fine with Wilder Wild's older version 2.4.6. on fabric 1.20.4. (Loader version 0.16.5)
The error on startup appears since Wilder Wild 3.0.0 through 3.0.2
Changing to an older Friends&Foes version doesn't help.
Latest Java 8 (8.0.4310.10)

**Logs**
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'friendsandfoes' at 'com.llamalad7.mixinextras.MixinExtrasBootstrap::init'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'friendsandfoes' at 'com.llamalad7.mixinextras.MixinExtrasBootstrap::init'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'friendsandfoes'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of com.llamalad7.mixinextras.MixinExtrasBootstrap failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 4 more
Caused by: java.lang.UnsupportedClassVersionError: net/frozenblock/lib/shadow/blue/endless/jankson/JsonGrammar has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.frozenblock.lib.config.api.instance.json.JsonType.<clinit>(JsonType.java:26)
	at net.frozenblock.wilderwild.config.WWMixinsConfig.<clinit>(WWMixinsConfig.java:35)
	at net.frozenblock.wilderwild.mixin.WilderWildMixinPlugin.onLoad(WilderWildMixinPlugin.java:40)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:790)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 13 more

**Additional context**
If it's because of Friends&Foes, I'll gladly forward it to them.

Thank you very much! 
Kind regards,
Martin

**Comment by EfficientStinkbug** [comment] 2024-10-27 08:19
Sorry, forget that. FrozenLib was missing. But shouldn't there be a message on startup, for the specific mod that's missing?

**Comment by AViewFromTheTop** [comment] 2024-10-27 15:22
??????

**Comment by AViewFromTheTop** [comment] 2024-10-27 15:23
Wtf is going on

**Comment by AViewFromTheTop** [comment] 2024-10-27 15:24
Not only is the first part confusing because the issue is a FrozenLib’s java thing not matching 1.20.4’s (which I tested and it was fine,) but then maple saplings only spawning leaves??? what?

**Comment by AViewFromTheTop** [comment] 2024-10-27 15:24
Can you send a screenshot for the maples?

**Comment by Treetrain1** [comment] 2024-10-27 21:33
Please try launching the game with a Java 21 runtime for now.

**Comment by EfficientStinkbug** [comment] 2024-10-28 18:46
Sorry for the confusing report. In summary:

The problem was just that FrozenLib was missing. (Installing the newest Java update didn't help)
Idk why it said in the crash report, that Friend&Foes was the problem. But usually the launcher informs you on startup, if a mod is missing. Strange, that it didn't notice me for the missing FrozenLib.


The thing with the maple saplings happens, when there is not enough space for them to grow. The saplings just disappear and then spawn the leaves instead. (Make sure that the grass is not covered with snow, etc.) I didn't notice that there wasn't enough space before and thought they just spawned leaves, lol

**But when testing, I've found a way worse bug:** When growing a maple sapling on a SERVER (same Java and fabric version), after around a minute, you get the following error attached below and your client crashes. You can't rejoin the world anymore and restarting the server also doesn't help. Just a backup works. The server itself doesn't crash or give any helpful info, when the client leaves.
I'm 99,9% sure it's because of the maple tree, because I tested it 3 times. After waiting around 15 minutes, the crash appeared very soon after growing the tree from a sapling with bone meal. 
(Note that the report says something about a physics mod, but that mod wasn't installed anymore)

[crash-2024-10-28_18.16.30-client.txt](https://github.com/user-attachments/files/1
[crash-2024-10-28_18.22.53-client.txt](https://github.com/user-attachments/files/17547398/crash-2024-10-28_18.22.53-client.txt)
![Screenshot 2024-10-28 181555](https://github.com/user-attachments/assets/c636698d-1a2c-4748-b0f5-39dce9cb5a66)

7547397/crash-2024-10-28_18.16.30-client.txt)

**Comment by AViewFromTheTop** [comment] 2024-10-31 15:35
That’s a lot of mods 😭
In any case, would you be able to try this with 3.0.3? It hasn’t fixed the saplings only generating leaves, but might fix the crash.

**Comment by AViewFromTheTop** [comment] 2024-10-31 18:54
Maple sapling issue fixed in 3.0.4

**Comment by AViewFromTheTop** [comment] 2024-11-01 21:47
Does this still occur with version 3.0.4?

**Closed** 2024-11-04 21:49 UTC
Labels: bug
