### ISSUE TITLE
Items From Stone Chests Don't Stack

### ISSUE THREAD

**Issue by BluePhoenixLOL** [FrozenBlock/WilderWild#105] opened 2022-08-21 22:37 UTC
the title says it all

**Comment by AViewFromTheTop** [comment] 2022-08-21 23:33
wth changed with stone chests to make this happen

**Comment by MerpisMe** [comment] 2022-08-21 23:34
it's only natural ones so i'm guessing it's to do with frozenlib

**Comment by AViewFromTheTop** [comment] 2022-08-21 23:36
> it's only natural ones so i'm guessing it's to do with frozenlib

should we just revert the frozenlib commits and call it a day

**Comment by MerpisMe** [comment] 2022-08-21 23:37
> should we just revert the frozenlib commits and call it a day

no because frozenlib is genuinely useful lol
the thing is that dropping the items apparently corrects their nbts so idk

**Comment by Treetrain1** [comment] 2022-08-21 23:37
> > it's only natural ones so i'm guessing it's to do with frozenlib
> 
> should we just revert the frozenlib commits and call it a day

nahhh

**Comment by Treetrain1** [comment] 2022-08-21 23:38
![image](https://user-images.githubusercontent.com/39657565/185815739-454ca2c6-11f0-4d4d-90fb-cdd396599d5f.png)
for me they work

**Comment by MerpisMe** [comment] 2022-08-21 23:38
try taking coal from the creative inventory and try stacking those to it

**Comment by Treetrain1** [comment] 2022-08-21 23:39
> try taking coal from the creative inventory and try stacking those to it

oh im stupid yeah that doesnt work

**Comment by Treetrain1** [comment] 2022-08-21 23:40
im pretty sure ive been experiencing this issue for a while

**Comment by AViewFromTheTop** [comment] 2022-08-21 23:46
> try taking coal from the creative inventory and try stacking those to it

Isn’t that fixed by just putting the ancient coal in your inventory
That’s a measure to stop players from losing their own items if the chest breaks
Now the fact that you can’t shift click them into the inventory with other coal is a pain but still

**Comment by MerpisMe** [comment] 2022-08-21 23:47
> > try taking coal from the creative inventory and try stacking those to it
> 
> Isn’t that fixed by just putting the ancient coal in your inventory That’s a measure to stop players from losing their own items if the chest breaks Now the fact that you can’t shift click them into the inventory with other coal is a pain but still

oh
uh maybe we have it remove the nbt on click and then calculate where to stack it to after that.. if that's even possible??????

**Comment by AViewFromTheTop** [comment] 2022-08-21 23:47
Ok my PC is freaking out rn because I’m trying to make SpongeBob mp4s and I can’t run anything else without it catching on fire
Do the items in stone chests all have at least 1 extra tag in them?

**Comment by MerpisMe** [comment] 2022-08-21 23:47
> Ok my PC is freaking out rn because I’m trying to make SpongeBob mp4s and I can’t run anything else without it catching on fire Do the items in stone chests all have at least 1 extra tag in them?

yes

**Comment by AViewFromTheTop** [comment] 2022-08-21 23:47
> yes

Ok and do they drop from the chests or not

**Comment by MerpisMe** [comment] 2022-08-21 23:48
> > yes
> 
> Ok and do they drop from the chests or not

they dont

**Comment by AViewFromTheTop** [comment] 2022-08-21 23:49
> they dont

Ok so the issue isn’t with “Applying Zero NBT,” it’s just that Ancient Horns don’t have an instrument tag
Items only drop from Ancient Stone Chests if they don’t have an ancient tag

**Comment by MerpisMe** [comment] 2022-08-21 23:49
> > they dont
> 
> Ok so the issue isn’t with “Applying Zero NBT,” it’s just that Ancient Horns don’t have an instrument tag Items only drop from Ancient Stone Chests if they don’t have an ancient tag

yeah i get that now i just thought it was an issue with no nbt since the items also werent stacking with other items
i didnt actually test it in game

**Comment by AViewFromTheTop** [comment] 2022-08-21 23:53
Bruh

**Comment by AViewFromTheTop** [comment] 2022-08-22 10:16
![27142602-072E-404B-AEAF-4FAF94F3CED0](https://user-images.githubusercontent.com/87103914/185898105-a4d9d2d9-8657-4842-9747-30ca3d5a57eb.jpeg)

**Comment by AViewFromTheTop** [comment] 2022-08-22 20:02
Fixed now, with the sideffect that you can shift-click INTO Ancient items as well. Good thing is that the Ancient tag gets removed anyway, so I don't care.

**Closed by AViewFromTheTop** 2022-08-22 20:02 UTC
Labels: bug, block, items, high priority

**Comment by MerpisMe** [comment] 2022-08-22 21:19
> Fixed now, with the sideffect that you can shift-click INTO Ancient items as well. Good thing is that the Ancient tag gets removed anyway, so I don't care.

oh sick
